### PR TITLE
feat: better popup ui closes #1

### LINKED ISSUE #1: Pop-up should be formatted to look better

### PR DESCRIPTION
**Pull request by oxalorg**
I have added a UI button for dismiss action, so when we add that feature we can just hook it up. #1 

The "Check it out" button does not take you anywhere at the moment as the schema does not have link stored separately (the reason for Issue #9 ). If this is not needed, I can remove it. 

Preview:
image

### CODE REVIEW

**Comment by anirudhvarma12** [comment]
It might be better to have a design where we can show multiple alternatives for a service?

**Comment by oxalorg** [comment]
Yes, I thought about it. It can always be added later on if needed :)

My main concern is that having a SINGLE CTA ("recommended alternative") reduces friction for the user. When presented with multiple alternatives, I almost always end up with neither and stick to my existing way of life (the paradox of choice maybe?).

**Comment by anirudhvarma12** [comment]
That is fair, having a single CTA definitely reduces friction. 

My only concern is that the schema currently allows multiple alternatives, and so showing only one (the first match) just feels a bit weird.

But before we update the UI to account for this, we should decide on the schema (#9) and if we want to show multiple alternatives. But this looks like a good start!

**Comment by oxalorg** [comment]
Based on the discussions in #1 and #9 

I've made the schema changes, and updated the UI. It now looks like this:

image

I've made the schema changes in this PR itself, and the code is kind of a spaghetti but it works! We can always improve it later on?

**Pull request closed without merging**
